maximum_availability_zones: 5
log_group_retention: 14

# Set to false when you want to create
# a fargate only ECS cluster.
enable_ec2_cluster: true
enable_rex_ray_plugin: false # by default this is false. this plugin helps to mount ebs volumes (use case: nosql databases file systems)
# Set to true when you want to create and
# attache a EFS mount to your ec2 ECS cluster.
# enable_ec2_cluster must be set to true
enable_efs: false

iam_policies:
  ecs-container-instance:
    action:
      - ecs:CreateCluster
      - ecs:DeregisterContainerInstance
      - ecs:DiscoverPollEndpoint
      - ecs:Poll
      - ecs:RegisterContainerInstance
      - ecs:StartTelemetrySession
      - ecs:Submit*
      - ecr:GetAuthorizationToken
      - ecr:BatchCheckLayerAvailability
      - ecr:GetDownloadUrlForLayer
      - ecr:BatchGetImage
      - logs:CreateLogStream
      - logs:PutLogEvents
  ecs-service-scheduler:
    action:
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:Describe*
      - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
      - elasticloadbalancing:DeregisterTargets
      - elasticloadbalancing:Describe*
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:RegisterTargets
